### ISSUE TITLE
[3pt] Viz output requirements

### ISSUE THREAD

**Issue by LauraKeys-NOAA** [NOAA-OWP/cahaba#111]
Viz team requesting post-processing of FIM 3 datasets as necessary to have the following outputs:

- hydrotable.csv rating curves reformatted as json files in following format: (values replacing <>)
{"<hydro id here>": {"stage_list": [0.0, 0.3048, 0.6096, <etc>], "q_list": [0.0, 9.311293553556311, 42.08217534559019, <etc>], "nwm_feature_id": <crosswalked nwm feature id here>}}
- catchments and hand output files renamed as previously discussed
- all HUC8 data in the above files compiled on a HUC6-basis

**Comment by BradfordBates-NOAA** [comment]
Related to #94

**Comment by BradfordBates-NOAA** [comment]
Related to #88

**Comment by LauraKeys-NOAA** [comment]
- hydrotable.csv rating curves reformatted as json files in following format: (values replacing <>)
{"\<fim3 id_here\>": {"stage_list": [0.0, 0.3048, 0.6096, \<etc\>], "q_list": [0.0, 9.311293553556311, 42.08217534559019, \<etc\>], "nwm_feature_id": \<nwm feature_id here\>}}

- catchments and hand output files renamed with suggested format 
\<folder: fim3_library\>
 -> \<folder: mainstems\>
    --> \<folder: huc code\>
         ---> catchments_\<huc code\>.tif
         ---> rating_curves_\<huc code\>.json         
         ---> hand_grid_\<huc code\>.tif
 -> \<folder: full-resolution\>
     -->
         --->

- all HUC8 data in the above files compiled on a HUC6-basis

**Comment by nickchadwick-noaa** [comment]
This may be a question for @BradfordBates-NOAA . I am not sure what files should be renamed to what in the outputs. From Brad, I got a list of "important files" in the outputs being:

- rem_zeroed_masked.tif
- gw_catchments_reaches_filtered_addedAttributes_crosswalked.gpkg
- gw_catchments_reaches_filtered_addedAttributes.tif
- hydroTable.csv
- src.json

Of those 5 files, which 3 are the ones that @LauraKeys-NOAA mention in her "suggested format".

Also, due to my lack of knowledge in hydrology, you're going to need to explain your last bullet point "all HUC8 data in the above files compiled on a HUC6-basis" a little bit more so I know how to go about formatting these files the way you want them.

The first bullet point of "hydrotable.csv rating curves reformatted as json..." should be straightforward.

**Comment by BradfordBates-NOAA** [comment]
- rem_zeroed_masked.tif = **_hand_grid_<huc code>.tif_**
- gw_catchments_reaches_filtered_addedAttributes.tif = **_catchments_<huc code>.tif_**
- src.json = _**rating_curves_<huc code>.json**_

Judging by the viz requirements, it will be necessary to add the "nwm_feature_id" key to the json in src.json, or perhaps when the _**rating_curves_<huc code>.json**_ is created, the "nwm_feature_id" key could be added. Let's discuss.

**Comment by LauraKeys-NOAA** [comment]
Yes, let me think about the NWM feature ID thing wrt the rating curves and
ask Corey what he thinks about having them in the SRC or as a separate file.

As for the HUC6 / HUC8 thing, the 6 or 8 (or 4 or 12, etc.) refers to how
many digits are used to specify a particular hydrologic unit. So the more
numbers, the more specific the watershed (and the smaller it is). A HUC6 is
split into lots of HUC8s; all the HUC8s in one HUC6 will have the first 6
digits the same (ex: 12030101 and 12030103 are 2 HUC8s in the HUC6 120301).
For the viz requirements, we'll want the rating curve data in one file
together, which is fairly straightforward to combine. Combining the
catchment and HAND grid tiffs might be less intuitive to Nick (more GIS
work), but we can work with you on it.

**Comment by LauraKeys-NOAA** [comment]
After talking to Corey about the crosswalk IDs, it'd be best for the Viz
outputs if the nwm_feature_id is included in the json file. (It'll be fewer
files to store and open, and I like that the NWM feature IDs will be
explicitly tied to the SRCs that were generated based on that particular
crosswalk alignment.) When and how in the process that happens is up to the
dev team.

**Comment by nickchadwick-noaa** [comment]
Most of this issue is being addressed in #88 . The only part that hasn't been addressed yet is your last requirement of "all HUC8 data in the above files compiled on a HUC6-basis" which will need to be a script of its own and is not in the scope of #88 .

Please checkout that linked issue and comment on if there are any problems with it.

**Comment by nickchadwick-noaa** [comment]
After talking to @BradfordBates-NOAA , rather than making another script that aggregates the HUC8 data into HUC6 outputs, we will instead just run the `fim_run.sh` at the HUC6 scale which will result in the HUC6 outputs that is required in this issue.

With that out of the way, this issue will be closed with the merging of #145 .

**Comment by frsalas-noaa** [comment]
@BradfordBates-NOAA @BrianAvant-NOAA @TrevorGrout-NOAA @RyanSpies-NOAA would like to understand the impact of producing the data on huc6 scale when we're assessing performance at huc8. I understand we've worked through some issues where results varied depending on the huc unit chosen to run the operation. A little concerned that assessment won't align with results.

**Comment by BrianAvant-NOAA** [comment]
There may be performance issues. As of now HUC6 and HUC8 scale do not produce exactly the same output (#4). I am working on a branch now to test this.

**Comment by BrianAvant-NOAA** [comment]
I think we should work with the HUC8 processing unit for FIM v3.0 and come up with a method to stitch them together to meet Viz requirements. This is what our eval metrics are based on. Going forward we will come up with a more robust solution for getting consistent results across different HUC scales.

**Comment by BradfordBates-NOAA** [comment]
I agree that long-term this should be the way to go. Although at the moment, we can continue to provide Viz with the HUC6-scale results to ensure our entire FIM-->Dev pipeline operates properly. The process modules can be refactored iteratively.

**Comment by nickchadwick-noaa** [comment]
So what it sounds like is we have a short-term solution for this after having merged in #145 and we will just need to create another issue to deal with the future solution of "stitching together" the outputs into whatever HUC scale we want the final outputs to be in.

If that sounds good, I'll close this issue and create a new one for this new feature to have in the backlog.

**Comment by BradfordBates-NOAA** [comment]
Yes let's do that. The requirements in this ticket have been addressed and, like you said, we can create a different and more specific ticket to address the stitching refactor.

**Comment by nickchadwick-noaa** [comment]
This conversation can be moved to #161
