### ISSUE TITLE
[6pt] Do Docker testing on personal laptop

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#178]

**Comment by mluck** [comment]
I get the following error when building the image from Dockerfile.dev:

send: spawn id exp3 not open
    while executing
"send -- "31\r""
    (file "./install_grass.exp" line 49)

The command '/bin/sh -c ./install_grass.exp' returned a non-zero code: 1

**Comment by frsalas-noaa** [comment]
@nickchadwick-noaa

**Comment by nickchadwick-noaa** [comment]
I am currently working with @mluck on resolving this issue. We are working through a few alternatives of using the "except" linux package, which is what is giving this error message.

The root of the problem seems to be when installing the grass package in the docker image via @mluck 's laptop, the interactive prompt is not available for the "except" package to simulate the inputs for selecting the language and keyboard layout. Instead, this error message appears:

```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
```

So we are first trying to bypass the keyboard settings altogether by forcing "non-interactive" mode when installing grass. If that doesn't work then we may have to try and set the "TERM" so that the except script can properly simulate the input needed to set the keyboard layout.

**Comment by mluck** [comment]
I was able to build the dev image successfully using the suggestion of @nickchadwick-noaa to use a noninteractive option in the grass install.

**Comment by mluck** [comment]
Unable to run acquire_and_preprocess_inputs.py or aggregate_vector_inputs.py from within dev container. Both result in a message that says "Killed". The issue occurs in the following lines:
- [acquire_and_preprocess_inputs.py:83] `wbd_hu8 = wbd_hu8.to_crs(PREP_PROJECTION)`
- [aggregate_vector_inputs.py:17] `nwm_streams = gpd.read_file(os.path.join(nwm_dir,'nwm_flows.gpkg'))`

Example of terminal output:
> root@941dd95ab3fa:/# /foss_fim/lib/acquire_and_preprocess_inputs.py -u 1209
> Making National WBD GPKG...
> 	WBDHU8
> Killed

> root@941dd95ab3fa:/# python3 /foss_fim/lib/aggregate_vector_inputs.py
> deriving NWM headwater points
> Killed

**Comment by BradfordBates-NOAA** [comment]
This can happen if the Docker container runs out of memory for the task. Copying @BrianAvant-NOAA to get him in the loop

**Comment by mluck** [comment]
That did seem to be the problem. I was able to get acquire_and_preprocess_inputs.py to run by increasing the memory allocation in Docker from 2GB (default) to 8GB (max), but aggregate_vector_inputs.py still fails with a "Killed" message.

**Comment by BradfordBates-NOAA** [comment]
I think the output from that script is already on the Google shared drive. If you would like to download it and keep testing other parts of the code, that could work while we look into the "killed" message more

![image](https://user-images.githubusercontent.com/69594899/103105439-7a877800-45f3-11eb-890c-f9954dc63409.png)

**Comment by mluck** [comment]
I was able to build and run the dev container but now am running into some memory problems. Problem #1, for the data I was able to run acquire_and_preprocess_inputs.py but I am getting a "Killed" (Docker out of memory) error running aggregate_vector_inputs.py (line 17). That is after increasing the Docker memory allocation to the max 8GB (default is 2GB) -- with the default 2GB acquire_and_preprocess_inputs.py also gets a Killed message (at line 84). Both errors occur while making calls to geopandas.
