### ISSUE TITLE
[13pt] Develop Python tool for evaluating and validating Manning's equation for flow-depth estimation inside grid cells.

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#204]

**Comment by BradfordBates-NOAA** [comment]
Part of #203

**Comment by BradfordBates-NOAA** [comment]
@HamedZamanisabzi-NOAA Would you say this script has been developed? Will you want to commit it to the cahaba repository?

**Comment by HamedZamanisabzi-NOAA** [comment]
Hi Brad,

As I explained it today. It has been created for one segment and I
progressed on two segments today as well. I hope tomorrow to complete it
and will early next week commit it to the repository.

Thanks,
Hamed Zamanisabzi

*GIS Hydro Scientist, **Contractor with Lynker in support of*

NOAA Office of Water Prediction | U.S. Department of Commerce

hamed.zamanisabzi@noaa.gov <bradford.bates@noaa.gov>

NOAA Affiliate, Lynker

**Comment by HamedZamanisabzi-NOAA** [comment]
The target for this task is to estimate the realistic flow surface profile through the channel segments. Since the slopes of the connected channel segments would change at the connection borders, flow surface profile will follow the Gradually Varied Flow or Rapidly Varied Flow till reaching the Normal Depth for that channel segment. The transitions from known depths at controlling points (such as break point between two segments, in which the slopes are different.) toward Normal Depths happens through different distances toward upstream or downstream. The required lengths for this transitions would be greater than the length of grid cells; therefore, depths within the channel segments should be adjusted based on the actual water surface elevations. Here are some of the potential flow profiles through channel segments:
![image](https://user-images.githubusercontent.com/75636003/104694006-2c383700-56d0-11eb-986c-99c9ea0ae33a.png)

**Comment by HamedZamanisabzi-NOAA** [comment]
![image](https://user-images.githubusercontent.com/75636003/104694134-5a1d7b80-56d0-11eb-9df4-6d8ee9445df3.png)

**Comment by HamedZamanisabzi-NOAA** [comment]
As an example: Here is a prismatic channel with two segments that slope of the channel changes from Mild to Streep:
![image](https://user-images.githubusercontent.com/75636003/104694290-9c46bd00-56d0-11eb-9885-13c2df397486.png)
![image](https://user-images.githubusercontent.com/75636003/104694299-a072da80-56d0-11eb-8978-17a1e5a3580d.png)

**Comment by HamedZamanisabzi-NOAA** [comment]
Considering the gradually varied flow conditions, energy equation would be used to calculate the flow profile within the transition lengths ( as an example within the M2 profile). The flow depth at the break point is Critical Depth and a Controlling Point to estimate the flow profile toward the upstream.  
![image](https://user-images.githubusercontent.com/75636003/104695175-f1370300-56d1-11eb-8698-38258fba0cd3.png)

![image](https://user-images.githubusercontent.com/75636003/104695216-001db580-56d2-11eb-848d-f24ee894cbc1.png)

**Comment by HamedZamanisabzi-NOAA** [comment]
![image](https://user-images.githubusercontent.com/75636003/104695297-20e60b00-56d2-11eb-9279-1952f8828782.png)

**Comment by HamedZamanisabzi-NOAA** [comment]
Ex. 1: Using the (Direct Step Method): Find the flow profile inside the channel within the Mild slope and calculate the required distance (channel length) where flow profile transition from critical depth to normal depth?
![image](https://user-images.githubusercontent.com/75636003/104695602-a2d63400-56d2-11eb-871b-84a4c6ba3c89.png)

**Comment by HamedZamanisabzi-NOAA** [comment]
![image](https://user-images.githubusercontent.com/75636003/104695845-f5afeb80-56d2-11eb-9dc9-70435d28b776.png)

**Comment by HamedZamanisabzi-NOAA** [comment]
![image](https://user-images.githubusercontent.com/75636003/104695879-07918e80-56d3-11eb-9ac2-8044d1152297.png)
![image](https://user-images.githubusercontent.com/75636003/104695895-0eb89c80-56d3-11eb-87b8-da2f255184b9.png)
![image](https://user-images.githubusercontent.com/75636003/104696026-3b6cb400-56d3-11eb-839d-bb2f81cac4b0.png)
The first profile has been created based on Python code using the step method and second profile has been simulated based on the Spreadsheet calculations: The simulated profiles for the transitions from critical depth at the break point (where the slope changes) are significantly similar.
