### ISSUE TITLE
[5pt] Missing mainstems segments near AHPS points.

### ISSUE THREAD

**Issue by TrevorGrout-NOAA** [NOAA-OWP/cahaba#397]
There appear to be missing mainstems segments near AHPS points. This is causing the output inundation mapping to be non-existent. One example site is ABBI3.
![image](https://user-images.githubusercontent.com/69653333/119570190-66e46700-bd75-11eb-8045-e444f0aa998d.png)

## Steps to replicate behavior (include URLs)

1.

**Comment by TrevorGrout-NOAA** [comment]
TCRK1 is another example where mainstems doesn't extend far enough:
![image](https://user-images.githubusercontent.com/69653333/119732788-446a5080-be3e-11eb-9ae0-a318316d50fa.png)

**Comment by BrianAvant-NOAA** [comment]
The issue related to ABBI3 has been identified and resolved. The NWS LID layer has changed recently and the NWM streams and catchments needed to be updated using the new LID layer. 

TCRK1 is caused by an issue with the WRDS API where the incorrect stream ID is referenced. There are multiple sites where this occurs. @TrevorGrout-NOAA are you going submit a ticket with the WRDS team on this?
